spring:
  profiles:
    active: local
  datasource:
#    url: jdbc:h2:tcp://localhost/~/nongbu
    url: jdbc:h2:~/nongbu
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  output:
    ansi:
      enabled: always

# 파라미터 확인을 위한 trace
logging:
  level:
    org.hibernate.type: trace

